language: node_js
install:
  - yarn install --production=false
script:
  - yarn lint
  - yarn ci:lint-docs
  - yarn build
  - yarn test
  - yarn codecov
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
